version: "3.8"

networks:
  pgadmin-network:
    name: pgadmin-network

services:

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - 4567:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - pgadmin-network

volumes:
  pgadmin-data:
    name: pgadmin-data
